apiVersion: apps/v1
kind: Deployment
metadata:
  name: wildwest
  namespace: default
spec:
  replicas: 5
  selector:
    matchLabels:
      app: wildwest
  template:
    metadata:
      labels:
        app: wildwest
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: wildwest
        image: registry.default.svc.cluster.local/wild-west-kubernetes:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: wildwest
  namespace: default
  labels:
    app: wildwest
spec:
  type: NodePort
  ports:
    - name: wildwest
      port: 8080
  selector:
    app: wildwest
